{
 "title": "Pelaez Bridge (Downstream)",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Water Level (m)",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"GeoSEDWaterLevel\")\r\n  |> range(start: -1h) // Define a time range, e.g., the last hour\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"water-level\") // Filter for the specific measurement\r\n  |> filter(fn: (r) => r[\"_field\"] == \"water_level\") // Filter for the specific field\r\n  |> filter(fn: (r) => r[\"location\"] == \"cdo-pelaez\") // Filter for the specific location\r\n  |> last() // Get the most recent value\r\n"
    }
   ]
  },
  {
   "title": "Water Velocity (m/s)",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"GeoSEDWaterFlowRate\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"water-flow-rate\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"flow_rate\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"cdo-pelaez\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "River Discharge (m3/s)",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"GeoSEDRiverDischarge\")\r\n  |> range(start: -1h) // Define a time range, e.g., the last hour\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"river-discharge\") // Filter for the specific measurement\r\n  |> filter(fn: (r) => r[\"_field\"] == \"discharge\") // Filter for the specific field\r\n  |> filter(fn: (r) => r[\"location\"] == \"cdo-pelaez\") // Filter for the specific location\r\n  |> last() // Get the most recent value\r\n"
    }
   ]
  },
  {
   "title": "Water Level Data",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"GeoSEDWaterLevel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"water-level\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"water_level\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"cdo-pelaez\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Water Velocity Data",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "query": "from(bucket: \"GeoSEDWaterFlowRate\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"water-flow-rate\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"flow_rate\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"cdo-pelaez\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "River Discharge Data",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "query": "from(bucket: \"GeoSEDRiverDischarge\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"river-discharge\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"discharge\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"cdo-pelaez\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}