{
 "title": "Pelaez Bridge (Downstream)",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Water Level (m)",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"GeoSEDWaterLevel\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"water-level\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"water_level\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"cdo-pelaez\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"lidar-lite\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Water Velocity (m/s)",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"GeoSEDWaterFlowRate\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"water-flow-rate\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"flow_rate\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"cdo-pelaez\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"camera\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "River Discharge (m3/s)",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"GeoSEDRiverDischarge\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"river-discharge\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"discharge\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"cdo-pelaez\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"camera\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Data Timestamp",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"GeoSEDTimeStamp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"sender\"] == \"GSD_001\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"cdo-pelaez\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"timestamp\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sent_time\")\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Water Level Data",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"GeoSEDWaterLevel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"water-level\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"water_level\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"cdo-pelaez\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"lidar-lite\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Water Velocity Data",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"GeoSEDWaterFlowRate\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"water-flow-rate\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"flow_rate\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"cdo-pelaez\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"camera\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "River Discharge Data",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "query": "from(bucket: \"GeoSEDRiverDischarge\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"river-discharge\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"discharge\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"cdo-pelaez\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"camera\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}