{
 "title": "Pelaez Device(Downstream)",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Device CPU Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"GeoSEDCPUUsage\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"location\"] == \"cdo-pelaez\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"raspberry-pi\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu-usage\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Device CPU Temperature (°C)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"GeoSEDCPUTemperature\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"location\"] == \"cdo-pelaez\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"raspberry-pi\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu-temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Device CPU Speed (MHz)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"GeoSEDCPUSpeed\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"location\"] == \"cdo-pelaez\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"raspberry-pi\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu-speed\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Data Timestamp",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"GeoSEDTimeStamp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"sender\"] == \"GSD_001\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"cdo-pelaez\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"timestamp\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sent_time\")\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Panel Temperature",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"GeoSEDTemperature\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"location\"] == \"cdo-pelaez\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"dht22\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Panel Humidity",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "query": "from(bucket: \"GeoSEDHumidity\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"location\"] == \"cdo-pelaez\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"dht22\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"humidity\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}